import { filePosition } from '@typedox/serialiser';
import { Highlighter } from 'shiki';
type purify = typeof import('dompurify');
export declare const sanitise: purify['sanitize'];
export declare let highlightTs: (codeString: string) => ReturnType<Highlighter['codeToHtml']>;
export declare function markedToHtmlString(string: string): string;
export declare function prettyTs(htmlString: string): Promise<string>;
export declare function initShikiTs(): Promise<void>;
export declare function stripComments(string: string): string;
export declare function highlightCodeAtPositions(position: filePosition, sourceText: string): Promise<string>;
export declare function formatLineNums(position: filePosition): string;
export {};
